CREATE SEQUENCE IF NOT EXISTS KARAOKE_SONG_SEQ INCREMENT 1;

CREATE TABLE IF NOT EXISTS KARAOKE_SONG
(
    id     SERIAL PRIMARY KEY,
    title  VARCHAR(255) NOT NULL,
    artist VARCHAR(255) NOT NULL,
    url    VARCHAR(255) NOT NULL
);
